---
- name: set rhdn username fact
  set_fact: user="{{ lookup('env','RHDN_USERNAME') }}"

- name: set rhdn password fact
  set_fact: password="{{ lookup('env','RHDN_PASSWORD') }}"

- name: set rhdn pool id fact
  set_fact: poolid="{{ lookup('env','RHDN_POOL_ID') }}"

- name: subscribe to repos
  redhat_subscription:
    state: present
    username: "{{ user }}"
    password: "{{ password }}"
    pool_ids: "{{ poolid }}"

- name: upgrade all packages
  yum:
    name: "*"
    state: latest
